#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: $0 --dafny /absolute/path/to/dafny --dotnet /absolute/path/to/dotnet --run-dir /absolute/path/to/new-directory [--repo-root /absolute/path]" >&2
  exit 64
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dafny=""
dotnet=""
run_dir=""
while (($#)); do
  case "$1" in
    --dafny) dafny="$2"; shift 2 ;;
    --dotnet) dotnet="$2"; shift 2 ;;
    --run-dir) run_dir="$2"; shift 2 ;;
    --repo-root) repo_root="$2"; shift 2 ;;
    *) usage ;;
  esac
done

[[ -n "$dafny" && -x "$dafny" && -n "$dotnet" && -x "$dotnet" && -n "$run_dir" ]] || usage
[[ ! -e "$run_dir" ]] || { echo "run directory already exists: $run_dir" >&2; exit 65; }
mkdir -p "$run_dir/a" "$run_dir/b" "$run_dir/logs"

for tool in git python3 timeout sha256sum; do
  command -v "$tool" >/dev/null || { echo "required tool unavailable: $tool" >&2; exit 69; }
done

expected_dafny_sha='e540b4826363afb87c326446239a682d45086905425fa6299c103eca9693846d'
actual_dafny_sha="$(sha256sum "$dafny" | cut -d' ' -f1)"
[[ "$actual_dafny_sha" == "$expected_dafny_sha" ]] || { echo "Dafny executable digest mismatch" >&2; exit 70; }
[[ "$($dafny --version)" == '4.11.0+fcb2042d6d043a2634f0854338c08feeaaaf4ae2' ]] || { echo "Dafny version mismatch" >&2; exit 70; }
[[ "$($dotnet --version)" == '10.0.400' ]] || { echo ".NET SDK version mismatch" >&2; exit 70; }

generate() {
  local lane="$1"
  "$dotnet" run --project "$repo_root/tests/Strogo.Modules.Portability.Conformance/Strogo.Modules.Portability.Conformance.csproj" -c Release -- \
    --dafny-out "$run_dir/$lane/candidate.dfy" \
    --weak-dafny-out "$run_dir/$lane/candidate-weak.dfy" \
    --report "$run_dir/$lane/contract.json" >"$run_dir/logs/generate-$lane.log" 2>&1
  grep -Eq '^PASS portability contract checks=[1-9][0-9]* valid=10 refusals=3 transport=24 mutations=4$' "$run_dir/logs/generate-$lane.log"
}

generate a
generate b

python3 - "$run_dir/a" "$run_dir/b" <<'PY'
import pathlib, sys
left, right = map(pathlib.Path, sys.argv[1:])
left_files = sorted(path.relative_to(left) for path in left.rglob('*') if path.is_file())
right_files = sorted(path.relative_to(right) for path in right.rglob('*') if path.is_file())
if left_files != right_files:
    raise SystemExit(f'generated file set differs: {left_files!r} != {right_files!r}')
for relative in left_files:
    if (left / relative).read_bytes() != (right / relative).read_bytes():
        raise SystemExit(f'generated bytes differ: {relative}')
PY

forbidden='Prover error:|Model parsing error|Could not parse any models|Unhandled exception|Internal error|Fatal error|ToolError'
verify_strong() {
  local lane="$1"
  local exit_code=0
  local log="$run_dir/logs/strong-$lane.log"
  timeout 180s "$dafny" verify "$run_dir/$lane/candidate.dfy" --enforce-determinism --cores 2 --verification-time-limit 30 >"$log" 2>&1 || exit_code=$?
  [[ "$exit_code" == 0 ]] || { cat "$log" >&2; echo "strong-$lane exit $exit_code" >&2; exit 71; }
  [[ $(wc -c <"$log") -le 1048576 ]] || { echo "strong-$lane exceeded output limit" >&2; exit 72; }
  ! grep -Eq "$forbidden" "$log" || { cat "$log" >&2; echo "strong-$lane emitted operational failure marker" >&2; exit 73; }
  grep -Fxq 'Dafny program verifier finished with 32 verified, 0 errors' "$log" || { cat "$log" >&2; exit 74; }
}

verify_strong a
verify_strong b

weak_exit=0
timeout 180s "$dafny" verify "$run_dir/a/candidate-weak.dfy" --enforce-determinism --cores 2 --verification-time-limit 30 >"$run_dir/logs/weak.log" 2>&1 || weak_exit=$?
[[ "$weak_exit" == 4 ]] || { cat "$run_dir/logs/weak.log" >&2; echo "weak exit $weak_exit" >&2; exit 75; }
[[ $(wc -c <"$run_dir/logs/weak.log") -le 1048576 ]] || { echo "weak output exceeded limit" >&2; exit 76; }
! grep -Eq "$forbidden" "$run_dir/logs/weak.log" || { cat "$run_dir/logs/weak.log" >&2; echo "weak emitted operational failure marker" >&2; exit 77; }
grep -Fxq 'Dafny program verifier finished with 31 verified, 1 error' "$run_dir/logs/weak.log" || { cat "$run_dir/logs/weak.log" >&2; exit 78; }
weak_line="$(python3 - "$run_dir/a/candidate-weak.obligations.json" <<'PY'
import json, sys
data=json.load(open(sys.argv[1], encoding='utf-8'))
print(next(item['line'] for item in data if item['id']=='owner-prefix-invariant'))
PY
)"
grep -Eq "candidate-weak\.dfy\(${weak_line},[0-9]+\): Related location: this is the postcondition that could not be proved" "$run_dir/logs/weak.log" || {
  cat "$run_dir/logs/weak.log" >&2
  echo "weak invariant failure was not linked to line $weak_line" >&2
  exit 79
}

python3 - "$run_dir" "$repo_root" "$actual_dafny_sha" <<'PY'
import hashlib, json, pathlib, platform, subprocess, sys
run, repo, dafny_sha = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), sys.argv[3]
sha=lambda p: hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
contract=json.loads((run/'a/contract.json').read_text(encoding='utf-8'))
report={
  'schemaVersion':'strogo.portability-proof-run.v0.1',
  'status':'Passed',
  'repositoryRevision':subprocess.check_output(['git','-C',str(repo),'rev-parse','HEAD'],text=True).strip(),
  'repositoryDirty':bool(subprocess.check_output(['git','-C',str(repo),'status','--porcelain'],text=True).strip()),
  'moduleDigest':contract['moduleDigest'],
  'ownerBundleDigest':contract['ownerBundleDigest'],
  'dafnySourceDigest':contract['dafnySourceDigest'],
  'proofIdentity':contract['proofIdentity'],
  'proofObligations':contract['proofObligations'],
  'twoCleanGeneration':'ByteEqual',
  'strongRuns':[{'lane':'a','outcome':'Verified','verified':'32','errors':'0','logSha256':sha(run/'logs/strong-a.log')},{'lane':'b','outcome':'Verified','verified':'32','errors':'0','logSha256':sha(run/'logs/strong-b.log')}],
  'weakInvariant':{'outcome':'Unproven','verified':'31','errors':'1','logSha256':sha(run/'logs/weak.log')},
  'toolchain':{'dafnyVersion':'4.11.0+fcb2042d6d043a2634f0854338c08feeaaaf4ae2','dafnyExecutableSha256':dafny_sha,'dotnetSdk':'10.0.400'},
  'environment':{'system':platform.system(),'release':platform.release(),'machine':platform.machine()}
}
(run/'report.json').write_text(json.dumps(report,ensure_ascii=True,separators=(',',':'))+'\n',encoding='utf-8',newline='\n')
PY

echo 'PASS portability mixed proof strong=32/0x2 weak=31/1'
